# Generated by Django 4.1.7 on 2023-03-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=37)),
                ('email', models.EmailField(max_length=47)),
                ('age', models.IntegerField(max_length=17)),
                ('gender', models.CharField(max_length=37)),
            ],
        ),
    ]
